### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by yanivefraim** [daniellmb/grunt-istanbul-coverage#23]
Not sure if this is possible already - is there an option to see detailed coverage view, like in grunt-istunbul? In this way, if coverage result is less than your threshold, you'll be able to see where is your problems and what tests you are missing...

**Comment by daniellmb** [comment]
Yes there is, you just need to configure the `html` reporter along with whatever else you have, such as `text-summary` or `lcov`.

https://github.com/daniellmb/console.style/blob/master/test/karma.conf.js#L41
