### ISSUE TITLE
Publish v0.1.4 to npm with grunt 1.0 support

### ISSUE THREAD

**Issue by tclindner** [daniellmb/grunt-istanbul-coverage#29]
Hi @daniellmb can you please publish v0.1.4 with grunt 1.0 support to npm? The last PR should have updated the version as the dependencies. Thank you!!

https://github.com/daniellmb/grunt-istanbul-coverage/pull/28

**Comment by daniellmb** [comment]
Done :)

**Comment by tclindner** [comment]
Thank you, @daniellmb!!
