### ISSUE TITLE
How to run coverage but still pass the build

### ISSUE THREAD

**Issue by benjaminapetersen** [daniellmb/grunt-istanbul-coverage#31]
Adding this to a project that is horribly behind on tests:

```
Running "coverage" task
Warning: ERROR: Coverage for statements (8.34%) does not meet threshold (90%)
ERROR: Coverage for branches (4.41%) does not meet threshold (90%)
ERROR: Coverage for lines (8.35%) does not meet threshold (90%)
ERROR: Coverage for functions (5.5%) does not meet threshold (90%) Use --force to continue.

Aborted due to warnings.

```

Is there an option to not fail the build?  This would be most useful to help encourage the team to write tests & bring the % up.

**Comment by daniellmb** [comment]
Sure, just [set your thresholds](https://github.com/daniellmb/grunt-istanbul-coverage#overview) lower...

```
thresholds: {
  'statements': 8,
  'branches': 4,
  'lines': 8,
  'functions': 5
}
```

**Comment by benjaminapetersen** [comment]
Hmm. Ideally I'd like to nag @ `90%` but still not fail, motivating us to get the coverage up. 
We could probably work with incrementally increasing the thresholds by a small `%` and see if that can work.

Thanks!
